[".config/nvim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-zoxide"]
    type = "git-repo"
    url = "https://github.com/jchook/ranger-zoxide.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-fzf-filter"]
    type = "git-repo"
    url = "https://github.com/MuXiu1997/ranger-fzf-filter.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-fzf-marks"]
    type = "git-repo"
    url = "https://github.com/laggardkernel/ranger-fzf-marks.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-archives"]
    type = "git-repo"
    url = "https://github.com/maximtrp/ranger-archives.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-cmus"]
    type = "git-repo"
    url = "https://github.com/maximtrp/ranger-cmus.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/ranger-devicons"]
    type = "git-repo"
    url = "https://github.com/alexanderjeurissen/ranger_devicons.git"
    refreshPeriod = "168h"
[".config/rofi/themes/gruvbox"]
    type = "git-repo"
    url = "https://github.com/bardisty/gruvbox-rofi.git"
    refreshPeriod = "168h"
["Repos/h-m-m"]
    type = "git-repo"
    url = "https://github.com/nadrad/h-m-m.git"
 ["Repos/ytfzf"]
    type = "git-repo"
    url = "https://github.com/pystardust/ytfzf.git"
    refreshPeriod = "168h"
 ["Repos/mutt-wizard"]
    type = "git-repo"
    url = "https://github.com/LukeSmithxyz/mutt-wizard.git"
    refreshPeriod = "168h"
 ["Repos/oil"]
    type = "git-repo"
    url = "https://github.com/AndreiUlmeyda/oil.git"
    refreshPeriod = "168h"
 ["Repos/pam-gnupg"]
    type = "git-repo"
    url = "https://github.com/cruegge/pam-gnupg.git"
    refreshPeriod = "168h"
 ["Repos/pass-tessen"]
    type = "git-repo"
    url = "https://github.com/ayushnix/pass-tessen.git"
    refreshPeriod = "168h"
