#!/usr/bin/env zsh
export ZDOTDIR="$HOME/.config/zsh"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=10000
export SAVEHIST=10000
export TERM='xterm-kitty'
export VISUAL='nvim'
export VIMCONFIG="$XDG_CONFIG_HOME/nvim"
export MANPAGER='nvim +Man!'
# fzf and ripgrep
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# default browser
export BROWSER="/usr/bin/firefox"
export WWW_HOME="https://duckduckgo.com/"
