[user_interface]
text_editor = "/usr/bin/nvim"
default_protocol = "SFTP"
show_hidden_files = true
check_for_updates = true
prompt_on_file_replace = true
notifications = true
notification_threshold = 536870912

[remote]
ssh_config = "/home/ssserpent/.ssh/config"

[remote.ssh_keys]
"ssserpent@samsung-wifi" = "/home/ssserpent/.config/termscp/.ssh/ssserpent@samsung-wifi.key"
"ssserpent@antix" = "/home/ssserpent/.config/termscp/.ssh/ssserpent@antix.key"
"ssserpent@samsung-lan" = "/home/ssserpent/.config/termscp/.ssh/ssserpent@samsung-lan.key"
